name: Ensure that pull request title starts with a gitmoji
description: The paralenz dev team uses gitmojies to generate changelogs. This action ensures that the PR title starts with one
author: Paralenz
runs:
    using: 'composite'
    steps:
        - name: Checkout the commit
          uses: actions/checkout@v2
        - name: Verify that pull request title starts with a gitmoji
          uses: deepakputhraya/action-pr-title@master
          with:
            allowed_prefixes: "🎨,:art:⚡️,:zap:,🔥,:fire:,🩹,:adhesive_bandage:,🐛,:bug:,🚑,:ambulance:,✨,:sparkles:,📝,:memo:,🚀,:rocket:,💄,:lipstick:,🎉,:tada:,✅,:white_check_mark:,🔒,:lock:,🔖,:bookmark:,🚨,:rotating_light:,🚧,:construction:,💚,:green_heart:,⬇️,:arrow_down:,⬆️,:arrow_up:,👷,:construction_worker:,📈,:chart_with_upwards_trend:,♻️,:recycle:,➕,:heavy_plus_sign:,➖,:heavy_minus_sign:,🔨,:hammer:,🔧,:wrench:,🌐,:globe_with_meridians:,✏️,:pencil2:,💩,:poop:,⏪,:rewind:,📦,:package:,👽,:alien:,🚚,:truck:,📄,:page_facing_up:,💥,:boom:,🍱,:bento:,♿️,:wheelchair:,💡,:bulb:,🍻,:beers:,💬,:speech_balloon:,🗃,:card_file_box:,🔊,:loud_sound:,🔇,:mute:,👥,:busts_in_silhouette:,🚸,:children_crossing:,🏗,:building_construction:,📱,:iphone:,🤡,:clown_face:,🥚,:egg:,🙈,:see_no_evil:,📸,:camera_flash:,⚗,:alembic:,🔍,:mag:,🏷️,:label:,🌱,:seedling:,🚩,:triangular_flag_on_post:,🥅,:goal_net:,💫,:dizzy:,🗑,:wastebasket:"
            min_length: 5
            max_length: 72