export const doNotEditDisclaimer: string = [
  '<br /><hr /><br />',
  `Last updated: ${new Date()}`,
  '<br />',
  '<br />',
  '<italic>',
  'This documentation is generated automaticlly. All changes to this file will be <bold>overwritten</bold>',
  '<br />',
  '<bold>DO NOT edit this file.</bold>',
  '</italic>'
].join('')
